#!/bin/bash

if [ "$1" = "-e" ]
then
	vim $0
	exit
fi

if [ $# -lt 1 ]
then
	echo "Usage: $0 MACHINE [-d|-e]"
	echo $(grep Host\  ../.ssh/config | sed 's#Host\ \([a-z0-9]*\)#\1#g' | implode ' ')
	exit
fi

usermachine=$1

if [ "$usermachine" = "local" ]
then
	cmd="screen -R -d -S chernjie"
elif [ "$2" = "-d" ]
then
	cmd="ssh -v $usermachine"
else
	cmd="ssh -v $usermachine -t screen -R -d -S chernjie"
fi

$cmd