#!/bin/bash

if [ $# -lt 1 ]
then
    echo "$0 [devlab|benjy]"
    exit
fi

case $1 in
    devlab ) usermachine='chernjie@dev_web02';;
    benjy  ) usermachine='chern.jie@benjy.local';;
esac

if [ -n "$usermachine" ]
then
    ssh -vt $usermachine screen -R -d -S chernjie
else
    echo "[ERROR] Invalid machine"
    echo "$0 [devlab|benjy]"
fi
